#!/usr/bin/env bash
declare -a videos=(
  "The Godfather (1972)"
  "The Godfather: Part II (1974)"
  "The Dark Knight (2008)"
  "12 Angry Men (1957)"
  "Schindler's List (1993)"
  "The Lord of the Rings: The Return of the King (2003)"
  "Pulp Fiction (1994)"
  "The Good, the Bad and the Ugly (1966)"
  "The Lord of the Rings: The Fellowship of the Ring (2001)"
)

for v in "${videos[@]}"; do
  ln -s "$PWD/videos/The Shawshank Redemption (1994).mp4" "$PWD/videos/$v.mp4"
done
